name: tag_bump

on:
  push:
    branches:
      - "main"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code
        with:
          fetch-depth: '0'

      # Verify only golang or Docker files have changed before we bump
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            go.*
            main.go

      - name: Bump version and push tag
        if: steps.changed_files.outputs.any_changed == 'true'
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch
          custom_release_rules: "bug:patch:Bug Fixes"
